// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtestcase__Syms.h"


VL_ATTR_COLD void Vtestcase___024root__trace_init_sub__TOP__0(Vtestcase___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtestcase__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtestcase___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushNamePrefix("testcase ");
    tracep->declBus(c+98,"Data_out", false,-1, 7,0);
    tracep->declBus(c+99,"Data_in", false,-1, 7,0);
    tracep->declBus(c+100,"Write_Out_File", false,-1, 31,0);
    tracep->pushNamePrefix("MYCASE ");
    tracep->declBus(c+101,"i", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("inst_harness ");
    tracep->declBus(c+115,"FAST_PERIOD", false,-1, 31,0);
    tracep->declBit(c+102,"Clock", false,-1);
    tracep->declBit(c+103,"Rst_n", false,-1);
    tracep->declBus(c+104,"Mpi_data", false,-1, 7,0);
    tracep->declBus(c+33,"Mpi_addr", false,-1, 5,0);
    tracep->declBit(c+34,"Mpi_cs_n", false,-1);
    tracep->declBit(c+35,"Mpi_rw", false,-1);
    tracep->pushNamePrefix("inst_BFM ");
    tracep->declBus(c+104,"uP_data", false,-1, 7,0);
    tracep->declBus(c+33,"uP_addr", false,-1, 5,0);
    tracep->declBit(c+34,"uP_cs_n", false,-1);
    tracep->declBit(c+35,"uP_rw", false,-1);
    tracep->declBus(c+36,"Data_out", false,-1, 7,0);
    tracep->declBit(c+37,"Data_oe", false,-1);
    tracep->declBus(c+116,"SLOW_PERIOD", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("u_MPI ");
    tracep->declBit(c+102,"Clock", false,-1);
    tracep->declBit(c+103,"Rst_n", false,-1);
    tracep->declBus(c+104,"Mpi_data", false,-1, 7,0);
    tracep->declBus(c+33,"Mpi_addr", false,-1, 5,0);
    tracep->declBit(c+34,"Mpi_cs_n", false,-1);
    tracep->declBit(c+35,"Mpi_rw", false,-1);
    tracep->declBit(c+94,"Cs_sample_sync", false,-1);
    tracep->declBit(c+95,"Cs_sample", false,-1);
    tracep->declBit(c+96,"Cs_sample_pipe", false,-1);
    tracep->declBit(c+97,"Mpi_enb", false,-1);
    tracep->declBit(c+105,"Dataout_enb", false,-1);
    tracep->declBus(c+104,"Data_in", false,-1, 7,0);
    tracep->declBus(c+106,"Data_out", false,-1, 7,0);
    tracep->pushNamePrefix("u_STM ");
    tracep->declBit(c+102,"Clock", false,-1);
    tracep->declBit(c+97,"Mpi_enb", false,-1);
    tracep->declBit(c+35,"Rw", false,-1);
    tracep->declBus(c+104,"Data_in", false,-1, 7,0);
    tracep->declBus(c+106,"Data_out", false,-1, 7,0);
    tracep->declBus(c+33,"Addr_in", false,-1, 5,0);
    tracep->declBit(c+107,"Ram_enb", false,-1);
    tracep->declBus(c+108,"Data_from_ram", false,-1, 7,0);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+78+i*1,"MyRegister", true,(i+0), 7,0);
    }
    tracep->pushNamePrefix("u_SPRAM ");
    tracep->declBus(c+38,"address", false,-1, 4,0);
    tracep->declBit(c+107,"clken", false,-1);
    tracep->declBit(c+102,"clock", false,-1);
    tracep->declBus(c+104,"data", false,-1, 7,0);
    tracep->declBit(c+39,"wren", false,-1);
    tracep->declBus(c+108,"q", false,-1, 7,0);
    tracep->declBus(c+108,"sub_wire0", false,-1, 7,0);
    tracep->pushNamePrefix("altsyncram_component ");
    tracep->declBus(c+117,"width_a", false,-1, 31,0);
    tracep->declBus(c+118,"widthad_a", false,-1, 31,0);
    tracep->declBus(c+119,"numwords_a", false,-1, 31,0);
    tracep->declArray(c+120,"outdata_reg_a", false,-1, 95,0);
    tracep->declBus(c+123,"address_aclr_a", false,-1, 31,0);
    tracep->declBus(c+123,"outdata_aclr_a", false,-1, 31,0);
    tracep->declBus(c+123,"indata_aclr_a", false,-1, 31,0);
    tracep->declBus(c+123,"wrcontrol_aclr_a", false,-1, 31,0);
    tracep->declBus(c+123,"byteena_aclr_a", false,-1, 31,0);
    tracep->declBus(c+124,"width_byteena_a", false,-1, 31,0);
    tracep->declBus(c+124,"width_b", false,-1, 31,0);
    tracep->declBus(c+124,"widthad_b", false,-1, 31,0);
    tracep->declBus(c+125,"numwords_b", false,-1, 31,0);
    tracep->declQuad(c+126,"rdcontrol_reg_b", false,-1, 47,0);
    tracep->declQuad(c+126,"address_reg_b", false,-1, 47,0);
    tracep->declArray(c+120,"outdata_reg_b", false,-1, 95,0);
    tracep->declBus(c+123,"outdata_aclr_b", false,-1, 31,0);
    tracep->declBus(c+123,"rdcontrol_aclr_b", false,-1, 31,0);
    tracep->declQuad(c+126,"indata_reg_b", false,-1, 47,0);
    tracep->declQuad(c+126,"wrcontrol_wraddress_reg_b", false,-1, 47,0);
    tracep->declQuad(c+126,"byteena_reg_b", false,-1, 47,0);
    tracep->declBus(c+123,"indata_aclr_b", false,-1, 31,0);
    tracep->declBus(c+123,"wrcontrol_aclr_b", false,-1, 31,0);
    tracep->declBus(c+123,"address_aclr_b", false,-1, 31,0);
    tracep->declBus(c+123,"byteena_aclr_b", false,-1, 31,0);
    tracep->declBus(c+124,"width_byteena_b", false,-1, 31,0);
    tracep->declQuad(c+128,"clock_enable_input_a", false,-1, 47,0);
    tracep->declQuad(c+130,"clock_enable_output_a", false,-1, 47,0);
    tracep->declQuad(c+128,"clock_enable_input_b", false,-1, 47,0);
    tracep->declQuad(c+128,"clock_enable_output_b", false,-1, 47,0);
    tracep->declArray(c+132,"operation_mode", false,-1, 87,0);
    tracep->declBus(c+117,"byte_size", false,-1, 31,0);
    tracep->declArray(c+135,"read_during_write_mode_mixed_ports", false,-1, 71,0);
    tracep->declBus(c+138,"ram_block_type", false,-1, 31,0);
    tracep->declQuad(c+139,"init_file", false,-1, 47,0);
    tracep->declQuad(c+139,"init_file_layout", false,-1, 47,0);
    tracep->declBus(c+125,"maximum_depth", false,-1, 31,0);
    tracep->declArray(c+141,"intended_device_family", false,-1, 79,0);
    tracep->declQuad(c+139,"lpm_hint", false,-1, 47,0);
    tracep->declArray(c+144,"lpm_type", false,-1, 79,0);
    tracep->declArray(c+135,"cread_during_write_mode_mixed_ports", false,-1, 71,0);
    tracep->declBus(c+147,"implement_in_les", false,-1, 23,0);
    tracep->declQuad(c+148,"power_up_uninitialized", false,-1, 39,0);
    tracep->declBus(c+125,"is_bidir_and_wrcontrol_addb_clk0", false,-1, 31,0);
    tracep->declBus(c+125,"is_bidir_and_wrcontrol_addb_clk1", false,-1, 31,0);
    tracep->declBus(c+125,"megaram_or_mram", false,-1, 31,0);
    tracep->declBus(c+125,"check_simultaneous_read_write", false,-1, 31,0);
    tracep->declBus(c+125,"dual_port_addreg_b_clk0", false,-1, 31,0);
    tracep->declBus(c+125,"dual_port_addreg_b_clk1", false,-1, 31,0);
    tracep->declBit(c+39,"wren_a", false,-1);
    tracep->declBit(c+150,"wren_b", false,-1);
    tracep->declBit(c+151,"rden_b", false,-1);
    tracep->declBus(c+104,"data_a", false,-1, 7,0);
    tracep->declBus(c+151,"data_b", false,-1, 0,0);
    tracep->declBus(c+38,"address_a", false,-1, 4,0);
    tracep->declBus(c+151,"address_b", false,-1, 0,0);
    tracep->declBit(c+102,"clock0", false,-1);
    tracep->declBit(c+151,"clock1", false,-1);
    tracep->declBit(c+107,"clocken0", false,-1);
    tracep->declBit(c+151,"clocken1", false,-1);
    tracep->declBit(c+150,"aclr0", false,-1);
    tracep->declBit(c+150,"aclr1", false,-1);
    tracep->declBus(c+151,"byteena_a", false,-1, 0,0);
    tracep->declBus(c+151,"byteena_b", false,-1, 0,0);
    tracep->declBit(c+150,"addressstall_a", false,-1);
    tracep->declBit(c+150,"addressstall_b", false,-1);
    tracep->declBus(c+108,"q_a", false,-1, 7,0);
    tracep->declBus(c+152,"q_b", false,-1, 0,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+40+i*1,"mem_data", true,(i+0), 7,0);
    }
    for (int i = 0; i < 2; ++i) {
        tracep->declBus(c+153+i*1,"mem_data_b", true,(i+0), 0,0);
    }
    tracep->declBus(c+73,"i_data_reg_a", false,-1, 7,0);
    tracep->declBus(c+155,"temp_wa", false,-1, 7,0);
    tracep->declBus(c+156,"temp_wa2", false,-1, 7,0);
    tracep->declBus(c+157,"temp_wa2b", false,-1, 7,0);
    tracep->declBus(c+1,"i_data_reg_b", false,-1, 0,0);
    tracep->declBus(c+158,"temp_wb", false,-1, 0,0);
    tracep->declBus(c+159,"temp_wb2", false,-1, 0,0);
    tracep->declBit(c+160,"temp", false,-1);
    tracep->declBus(c+2,"i_q_reg_a", false,-1, 7,0);
    tracep->declBus(c+108,"i_q_tmp_a", false,-1, 7,0);
    tracep->declBus(c+109,"i_q_tmp2_a", false,-1, 7,0);
    tracep->declBus(c+3,"i_q_reg_b", false,-1, 0,0);
    tracep->declBus(c+4,"i_q_tmp_b", false,-1, 0,0);
    tracep->declBus(c+5,"i_q_tmp2_b", false,-1, 0,0);
    tracep->declBus(c+74,"i_byteena_mask_reg_a", false,-1, 7,0);
    tracep->declBus(c+6,"i_byteena_mask_reg_b", false,-1, 0,0);
    tracep->declBus(c+75,"i_address_reg_a", false,-1, 4,0);
    tracep->declBus(c+7,"i_address_reg_b", false,-1, 0,0);
    tracep->declBus(c+161,"i_byteena_mask_reg_a_tmp", false,-1, 7,0);
    tracep->declBus(c+162,"i_byteena_mask_reg_b_tmp", false,-1, 0,0);
    tracep->declBus(c+110,"i_byteena_mask_reg_a_out", false,-1, 7,0);
    tracep->declBus(c+163,"i_byteena_mask_reg_b_out", false,-1, 0,0);
    tracep->declBus(c+76,"i_byteena_mask_reg_a_x", false,-1, 7,0);
    tracep->declBus(c+8,"i_byteena_mask_reg_b_x", false,-1, 0,0);
    tracep->declArray(c+164,"ram_initf", false,-1, 2048,1);
    tracep->declBit(c+77,"i_wren_reg_a", false,-1);
    tracep->declBit(c+9,"i_wren_reg_b", false,-1);
    tracep->declBit(c+10,"i_rden_reg_b", false,-1);
    tracep->declBit(c+111,"i_read_flag_a", false,-1);
    tracep->declBit(c+11,"i_read_flag_b", false,-1);
    tracep->declBit(c+112,"i_write_flag_a", false,-1);
    tracep->declBit(c+12,"i_write_flag_b", false,-1);
    tracep->declBit(c+113,"good_to_go_a", false,-1);
    tracep->declBit(c+13,"good_to_go_b", false,-1);
    tracep->declBus(c+228,"file_desc", false,-1, 31,0);
    tracep->declBit(c+229,"init_file_b_port", false,-1);
    tracep->declBit(c+114,"i_nmram_write_a", false,-1);
    tracep->declBit(c+14,"i_nmram_write_b", false,-1);
    tracep->declBus(c+15,"wa_mult_x", false,-1, 7,0);
    tracep->declBus(c+230,"wa_mult_x_ii", false,-1, 7,0);
    tracep->declBus(c+231,"wa_mult_x_iii", false,-1, 7,0);
    tracep->declBus(c+232,"add_reg_a_mult_wa", false,-1, 12,0);
    tracep->declBus(c+233,"add_reg_b_mult_wb", false,-1, 1,0);
    tracep->declBus(c+234,"add_reg_a_mult_wa_pl_wa", false,-1, 12,0);
    tracep->declBus(c+235,"add_reg_b_mult_wb_pl_wb", false,-1, 1,0);
    tracep->declBit(c+150,"i_indata_aclr_a", false,-1);
    tracep->declBit(c+150,"i_address_aclr_a", false,-1);
    tracep->declBit(c+150,"i_wrcontrol_aclr_a", false,-1);
    tracep->declBit(c+150,"i_indata_aclr_b", false,-1);
    tracep->declBit(c+150,"i_address_aclr_b", false,-1);
    tracep->declBit(c+150,"i_wrcontrol_aclr_b", false,-1);
    tracep->declBit(c+150,"i_outdata_aclr_a", false,-1);
    tracep->declBit(c+150,"i_outdata_aclr_b", false,-1);
    tracep->declBit(c+150,"i_rdcontrol_aclr_b", false,-1);
    tracep->declBit(c+150,"i_byteena_aclr_a", false,-1);
    tracep->declBit(c+150,"i_byteena_aclr_b", false,-1);
    tracep->declBit(c+150,"i_outdata_clk_a", false,-1);
    tracep->declBit(c+151,"i_outdata_clken_a", false,-1);
    tracep->declBit(c+150,"i_outdata_clk_b", false,-1);
    tracep->declBit(c+151,"i_outdata_clken_b", false,-1);
    tracep->declBit(c+107,"i_clocken0", false,-1);
    tracep->declBit(c+151,"i_clocken1", false,-1);
    tracep->declBit(c+107,"i_clocken0_b", false,-1);
    tracep->declBus(c+151,"i_byteena_a", false,-1, 0,0);
    tracep->declBus(c+151,"i_byteena_b", false,-1, 0,0);
    tracep->declBus(c+16,"i_numwords_a", false,-1, 31,0);
    tracep->declBus(c+17,"i_numwords_b", false,-1, 31,0);
    tracep->declBus(c+72,"i_aclr_flag_a", false,-1, 31,0);
    tracep->declBus(c+18,"i_aclr_flag_b", false,-1, 31,0);
    tracep->declBus(c+236,"i_q_tmp2_a_idx", false,-1, 31,0);
    tracep->declBus(c+19,"i", false,-1, 31,0);
    tracep->declBus(c+237,"i2", false,-1, 31,0);
    tracep->declBus(c+238,"i3", false,-1, 31,0);
    tracep->declBus(c+239,"i4", false,-1, 31,0);
    tracep->declBus(c+240,"i5", false,-1, 31,0);
    tracep->declBus(c+241,"j", false,-1, 31,0);
    tracep->declBus(c+242,"j2", false,-1, 31,0);
    tracep->declBus(c+243,"k", false,-1, 31,0);
    tracep->declBus(c+244,"k2", false,-1, 31,0);
    tracep->declBus(c+245,"k3", false,-1, 31,0);
    tracep->declBus(c+246,"k4", false,-1, 31,0);
    tracep->declBus(c+247,"i_div_wa", false,-1, 31,0);
    tracep->declBus(c+248,"j_plus_i2", false,-1, 31,0);
    tracep->declBus(c+249,"j2_plus_i5", false,-1, 31,0);
    tracep->declBus(c+250,"j_plus_i2_div_a", false,-1, 31,0);
    tracep->declBus(c+251,"j2_plus_i5_div_a", false,-1, 31,0);
    tracep->pushNamePrefix("dev ");
    tracep->declBit(c+252,"IS_FAMILY_ACEX1K__Vstatic__is_acex1k", false,-1);
    tracep->declBit(c+253,"IS_FAMILY_APEX20K__Vstatic__is_apex20k", false,-1);
    tracep->declBit(c+254,"IS_FAMILY_APEX20KC__Vstatic__is_apex20kc", false,-1);
    tracep->declBit(c+255,"IS_FAMILY_APEX20KE__Vstatic__is_apex20ke", false,-1);
    tracep->declBit(c+256,"IS_FAMILY_APEXII__Vstatic__is_apexii", false,-1);
    tracep->declBit(c+257,"IS_FAMILY_EXCALIBUR_ARM__Vstatic__is_excalibur_arm", false,-1);
    tracep->declBit(c+258,"IS_FAMILY_FLEX10KE__Vstatic__is_flex10ke", false,-1);
    tracep->declBit(c+259,"IS_FAMILY_MERCURY__Vstatic__is_mercury", false,-1);
    tracep->declBit(c+20,"IS_FAMILY_STRATIX__Vstatic__is_stratix", false,-1);
    tracep->declBit(c+21,"IS_FAMILY_STRATIXGX__Vstatic__is_stratixgx", false,-1);
    tracep->declBit(c+260,"IS_FAMILY_CYCLONE__Vstatic__is_cyclone", false,-1);
    tracep->declBit(c+261,"IS_FAMILY_MAXII__Vstatic__is_maxii", false,-1);
    tracep->declBit(c+22,"IS_FAMILY_HARDCOPYSTRATIX__Vstatic__is_hardcopystratix", false,-1);
    tracep->declBit(c+23,"IS_FAMILY_STRATIXII__Vstatic__is_stratixii", false,-1);
    tracep->declBit(c+24,"IS_FAMILY_STRATIXIIGX__Vstatic__is_stratixiigx", false,-1);
    tracep->declBit(c+25,"IS_FAMILY_CYCLONEII__Vstatic__is_cycloneii", false,-1);
    tracep->declBit(c+26,"IS_FAMILY_HARDCOPYII__Vstatic__is_hardcopyii", false,-1);
    tracep->declBit(c+262,"FEATURE_FAMILY_STRATIXGX__Vstatic__var_family_stratixgx", false,-1);
    tracep->declBit(c+263,"FEATURE_FAMILY_CYCLONE__Vstatic__var_family_cyclone", false,-1);
    tracep->declBit(c+27,"FEATURE_FAMILY_STRATIXII__Vstatic__var_family_stratixii", false,-1);
    tracep->declBit(c+28,"FEATURE_FAMILY_STRATIX_HC__Vstatic__var_family_stratix_hc", false,-1);
    tracep->declBit(c+264,"FEATURE_FAMILY_STRATIX__Vstatic__var_family_stratix", false,-1);
    tracep->declBit(c+265,"FEATURE_FAMILY_MAXII__Vstatic__var_family_maxii", false,-1);
    tracep->declBit(c+29,"FEATURE_FAMILY_CYCLONEII__Vstatic__var_family_cycloneii", false,-1);
    tracep->declBit(c+30,"FEATURE_FAMILY_HAS_MEGARAM__Vstatic__var_family_has_megaram", false,-1);
    tracep->declBit(c+31,"FEATURE_FAMILY_HAS_M512__Vstatic__var_family_has_m512", false,-1);
    tracep->declBit(c+32,"FEATURE_FAMILY_HAS_STRATIXII_STYLE_RAM__Vstatic__var_family_has_stratixii_style_ram", false,-1);
    tracep->declBit(c+266,"FEATURE_FAMILY_HAS_INVERTED_OUTPUT_DDIO__Vstatic__var_family_has_inverted_output_ddio", false,-1);
    tracep->declBit(c+267,"IS_VALID_FAMILY__Vstatic__is_valid", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("mem ");
    tracep->declBus(c+268,"convert_hex2ver__Vstatic__c", false,-1, 8,1);
    tracep->declBus(c+269,"convert_hex2ver__Vstatic__hex", false,-1, 3,0);
    tracep->declBus(c+270,"convert_hex2ver__Vstatic__tmp_char", false,-1, 3,0);
    tracep->declBus(c+271,"convert_hex2ver__Vstatic__ifp", false,-1, 31,0);
    tracep->declBus(c+272,"convert_hex2ver__Vstatic__ofp", false,-1, 31,0);
    tracep->declBus(c+273,"convert_hex2ver__Vstatic__r", false,-1, 31,0);
    tracep->declBus(c+274,"convert_hex2ver__Vstatic__r2", false,-1, 31,0);
    tracep->declBus(c+275,"convert_hex2ver__Vstatic__i", false,-1, 31,0);
    tracep->declBus(c+276,"convert_hex2ver__Vstatic__j", false,-1, 31,0);
    tracep->declBus(c+277,"convert_hex2ver__Vstatic__k", false,-1, 31,0);
    tracep->declBus(c+278,"convert_hex2ver__Vstatic__m", false,-1, 31,0);
    tracep->declBus(c+279,"convert_hex2ver__Vstatic__n", false,-1, 31,0);
    tracep->declBus(c+280,"convert_hex2ver__Vstatic__done", false,-1, 31,0);
    tracep->declBus(c+281,"convert_hex2ver__Vstatic__error_status", false,-1, 31,0);
    tracep->declBus(c+282,"convert_hex2ver__Vstatic__first_rec", false,-1, 31,0);
    tracep->declBus(c+283,"convert_hex2ver__Vstatic__last_rec", false,-1, 31,0);
    tracep->declBus(c+284,"convert_hex2ver__Vstatic__off_addr", false,-1, 31,0);
    tracep->declBus(c+285,"convert_hex2ver__Vstatic__nn", false,-1, 31,0);
    tracep->declBus(c+286,"convert_hex2ver__Vstatic__aaaa", false,-1, 31,0);
    tracep->declBus(c+287,"convert_hex2ver__Vstatic__tt", false,-1, 31,0);
    tracep->declBus(c+288,"convert_hex2ver__Vstatic__cc", false,-1, 31,0);
    tracep->declBus(c+289,"convert_hex2ver__Vstatic__aah", false,-1, 31,0);
    tracep->declBus(c+290,"convert_hex2ver__Vstatic__aal", false,-1, 31,0);
    tracep->declBus(c+291,"convert_hex2ver__Vstatic__dd", false,-1, 31,0);
    tracep->declBus(c+292,"convert_hex2ver__Vstatic__sum", false,-1, 31,0);
    tracep->declBus(c+293,"convert_hex2ver__Vstatic__line_no", false,-1, 31,0);
    tracep->popNamePrefix(7);
}

VL_ATTR_COLD void Vtestcase___024root__trace_init_top(Vtestcase___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtestcase__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtestcase___024root__trace_init_top\n"); );
    // Body
    Vtestcase___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtestcase___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtestcase___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtestcase___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtestcase___024root__trace_register(Vtestcase___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtestcase__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtestcase___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtestcase___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtestcase___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtestcase___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtestcase___024root__trace_full_sub_0(Vtestcase___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtestcase___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtestcase___024root__trace_full_top_0\n"); );
    // Init
    Vtestcase___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtestcase___024root*>(voidSelf);
    Vtestcase__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtestcase___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtestcase___024root__trace_full_sub_0(Vtestcase___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtestcase__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtestcase___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    VlWide<3>/*95:0*/ __Vtemp_1;
    VlWide<3>/*95:0*/ __Vtemp_2;
    VlWide<3>/*95:0*/ __Vtemp_3;
    VlWide<3>/*95:0*/ __Vtemp_4;
    VlWide<3>/*95:0*/ __Vtemp_5;
    // Body
    bufp->fullBit(oldp+1,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_data_reg_b));
    bufp->fullCData(oldp+2,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_reg_a),8);
    bufp->fullBit(oldp+3,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_reg_b));
    bufp->fullBit(oldp+4,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp_b));
    bufp->fullBit(oldp+5,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp2_b));
    bufp->fullBit(oldp+6,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b));
    bufp->fullBit(oldp+7,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_address_reg_b));
    bufp->fullBit(oldp+8,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x));
    bufp->fullBit(oldp+9,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_wren_reg_b));
    bufp->fullBit(oldp+10,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_rden_reg_b));
    bufp->fullBit(oldp+11,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_read_flag_b));
    bufp->fullBit(oldp+12,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_write_flag_b));
    bufp->fullBit(oldp+13,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__good_to_go_b));
    bufp->fullBit(oldp+14,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_nmram_write_b));
    bufp->fullCData(oldp+15,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__wa_mult_x),8);
    bufp->fullIData(oldp+16,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_numwords_a),32);
    bufp->fullIData(oldp+17,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_numwords_b),32);
    bufp->fullIData(oldp+18,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_aclr_flag_b),32);
    bufp->fullIData(oldp+19,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i),32);
    bufp->fullBit(oldp+20,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_STRATIX__Vstatic__is_stratix));
    bufp->fullBit(oldp+21,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_STRATIXGX__Vstatic__is_stratixgx));
    bufp->fullBit(oldp+22,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_HARDCOPYSTRATIX__Vstatic__is_hardcopystratix));
    bufp->fullBit(oldp+23,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_STRATIXII__Vstatic__is_stratixii));
    bufp->fullBit(oldp+24,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_STRATIXIIGX__Vstatic__is_stratixiigx));
    bufp->fullBit(oldp+25,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_CYCLONEII__Vstatic__is_cycloneii));
    bufp->fullBit(oldp+26,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_HARDCOPYII__Vstatic__is_hardcopyii));
    bufp->fullBit(oldp+27,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_STRATIXII__Vstatic__var_family_stratixii));
    bufp->fullBit(oldp+28,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_STRATIX_HC__Vstatic__var_family_stratix_hc));
    bufp->fullBit(oldp+29,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_CYCLONEII__Vstatic__var_family_cycloneii));
    bufp->fullBit(oldp+30,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_HAS_MEGARAM__Vstatic__var_family_has_megaram));
    bufp->fullBit(oldp+31,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_HAS_M512__Vstatic__var_family_has_m512));
    bufp->fullBit(oldp+32,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_HAS_STRATIXII_STYLE_RAM__Vstatic__var_family_has_stratixii_style_ram));
    bufp->fullCData(oldp+33,(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_addr),6);
    bufp->fullBit(oldp+34,(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_cs_n));
    bufp->fullBit(oldp+35,(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_rw));
    bufp->fullCData(oldp+36,(vlSelf->testcase__DOT__inst_harness__DOT__inst_BFM__DOT__Data_out),8);
    bufp->fullBit(oldp+37,(vlSelf->testcase__DOT__inst_harness__DOT__inst_BFM__DOT__Data_oe));
    bufp->fullCData(oldp+38,((0x1fU & (IData)(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_addr))),5);
    bufp->fullBit(oldp+39,((1U & (~ (IData)(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_rw)))));
    bufp->fullCData(oldp+40,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[0]),8);
    bufp->fullCData(oldp+41,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[1]),8);
    bufp->fullCData(oldp+42,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[2]),8);
    bufp->fullCData(oldp+43,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[3]),8);
    bufp->fullCData(oldp+44,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[4]),8);
    bufp->fullCData(oldp+45,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[5]),8);
    bufp->fullCData(oldp+46,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[6]),8);
    bufp->fullCData(oldp+47,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[7]),8);
    bufp->fullCData(oldp+48,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[8]),8);
    bufp->fullCData(oldp+49,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[9]),8);
    bufp->fullCData(oldp+50,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[10]),8);
    bufp->fullCData(oldp+51,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[11]),8);
    bufp->fullCData(oldp+52,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[12]),8);
    bufp->fullCData(oldp+53,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[13]),8);
    bufp->fullCData(oldp+54,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[14]),8);
    bufp->fullCData(oldp+55,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[15]),8);
    bufp->fullCData(oldp+56,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[16]),8);
    bufp->fullCData(oldp+57,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[17]),8);
    bufp->fullCData(oldp+58,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[18]),8);
    bufp->fullCData(oldp+59,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[19]),8);
    bufp->fullCData(oldp+60,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[20]),8);
    bufp->fullCData(oldp+61,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[21]),8);
    bufp->fullCData(oldp+62,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[22]),8);
    bufp->fullCData(oldp+63,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[23]),8);
    bufp->fullCData(oldp+64,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[24]),8);
    bufp->fullCData(oldp+65,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[25]),8);
    bufp->fullCData(oldp+66,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[26]),8);
    bufp->fullCData(oldp+67,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[27]),8);
    bufp->fullCData(oldp+68,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[28]),8);
    bufp->fullCData(oldp+69,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[29]),8);
    bufp->fullCData(oldp+70,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[30]),8);
    bufp->fullCData(oldp+71,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data[31]),8);
    bufp->fullIData(oldp+72,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_aclr_flag_a),32);
    bufp->fullCData(oldp+73,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_data_reg_a),8);
    bufp->fullCData(oldp+74,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a),8);
    bufp->fullCData(oldp+75,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_address_reg_a),5);
    bufp->fullCData(oldp+76,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x),8);
    bufp->fullBit(oldp+77,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_wren_reg_a));
    bufp->fullCData(oldp+78,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[0]),8);
    bufp->fullCData(oldp+79,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[1]),8);
    bufp->fullCData(oldp+80,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[2]),8);
    bufp->fullCData(oldp+81,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[3]),8);
    bufp->fullCData(oldp+82,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[4]),8);
    bufp->fullCData(oldp+83,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[5]),8);
    bufp->fullCData(oldp+84,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[6]),8);
    bufp->fullCData(oldp+85,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[7]),8);
    bufp->fullCData(oldp+86,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[8]),8);
    bufp->fullCData(oldp+87,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[9]),8);
    bufp->fullCData(oldp+88,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[10]),8);
    bufp->fullCData(oldp+89,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[11]),8);
    bufp->fullCData(oldp+90,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[12]),8);
    bufp->fullCData(oldp+91,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[13]),8);
    bufp->fullCData(oldp+92,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[14]),8);
    bufp->fullCData(oldp+93,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister[15]),8);
    bufp->fullBit(oldp+94,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__Cs_sample_sync));
    bufp->fullBit(oldp+95,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__Cs_sample));
    bufp->fullBit(oldp+96,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__Cs_sample_pipe));
    bufp->fullBit(oldp+97,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__Mpi_enb));
    bufp->fullCData(oldp+98,(vlSelf->testcase__DOT__Data_out),8);
    bufp->fullCData(oldp+99,(vlSelf->testcase__DOT__Data_in),8);
    bufp->fullIData(oldp+100,(vlSelf->testcase__DOT__Write_Out_File),32);
    bufp->fullIData(oldp+101,(vlSelf->testcase__DOT__MYCASE__DOT__i),32);
    bufp->fullBit(oldp+102,(vlSelf->testcase__DOT__inst_harness__DOT__Clock));
    bufp->fullBit(oldp+103,(vlSelf->testcase__DOT__inst_harness__DOT__Rst_n));
    bufp->fullCData(oldp+104,(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_data),8);
    bufp->fullBit(oldp+105,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__Dataout_enb));
    bufp->fullCData(oldp+106,(((0x20U & (IData)(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_addr))
                                ? vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__MyRegister
                               [(0xfU & (IData)(vlSelf->testcase__DOT__inst_harness__DOT__Mpi_addr))]
                                : (IData)(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp_a))),8);
    bufp->fullBit(oldp+107,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__Ram_enb));
    bufp->fullCData(oldp+108,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp_a),8);
    bufp->fullCData(oldp+109,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp2_a),8);
    bufp->fullCData(oldp+110,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out),8);
    bufp->fullBit(oldp+111,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_read_flag_a));
    bufp->fullBit(oldp+112,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_write_flag_a));
    bufp->fullBit(oldp+113,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__good_to_go_a));
    bufp->fullBit(oldp+114,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_nmram_write_a));
    bufp->fullIData(oldp+115,(0xaU),32);
    bufp->fullIData(oldp+116,(0x18U),32);
    bufp->fullIData(oldp+117,(8U),32);
    bufp->fullIData(oldp+118,(5U),32);
    bufp->fullIData(oldp+119,(0x20U),32);
    __Vtemp_1[0U] = 0x45524544U;
    __Vtemp_1[1U] = 0x47495354U;
    __Vtemp_1[2U] = 0x554e5245U;
    bufp->fullWData(oldp+120,(__Vtemp_1),96);
    bufp->fullIData(oldp+123,(0x4e4f4e45U),32);
    bufp->fullIData(oldp+124,(1U),32);
    bufp->fullIData(oldp+125,(0U),32);
    bufp->fullQData(oldp+126,(0x434c4f434b31ULL),48);
    bufp->fullQData(oldp+128,(0x4e4f524d414cULL),48);
    bufp->fullQData(oldp+130,(0x425950415353ULL),48);
    __Vtemp_2[0U] = 0x504f5254U;
    __Vtemp_2[1U] = 0x474c455fU;
    __Vtemp_2[2U] = 0x53494eU;
    bufp->fullWData(oldp+132,(__Vtemp_2),88);
    __Vtemp_3[0U] = 0x43415245U;
    __Vtemp_3[1U] = 0x4f4e545fU;
    __Vtemp_3[2U] = 0x44U;
    bufp->fullWData(oldp+135,(__Vtemp_3),72);
    bufp->fullIData(oldp+138,(0x4d353132U),32);
    bufp->fullQData(oldp+139,(0x554e55534544ULL),48);
    __Vtemp_4[0U] = 0x78204949U;
    __Vtemp_4[1U] = 0x72617469U;
    __Vtemp_4[2U] = 0x5374U;
    bufp->fullWData(oldp+141,(__Vtemp_4),80);
    __Vtemp_5[0U] = 0x6372616dU;
    __Vtemp_5[1U] = 0x7473796eU;
    __Vtemp_5[2U] = 0x616cU;
    bufp->fullWData(oldp+144,(__Vtemp_5),80);
    bufp->fullIData(oldp+147,(0x4f4646U),24);
    bufp->fullQData(oldp+148,(0x46414c5345ULL),40);
    bufp->fullBit(oldp+150,(0U));
    bufp->fullBit(oldp+151,(1U));
    bufp->fullBit(oldp+152,(0U));
    bufp->fullBit(oldp+153,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data_b[0]));
    bufp->fullBit(oldp+154,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem_data_b[1]));
    bufp->fullCData(oldp+155,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp_wa),8);
    bufp->fullCData(oldp+156,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp_wa2),8);
    bufp->fullCData(oldp+157,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp_wa2b),8);
    bufp->fullBit(oldp+158,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp_wb));
    bufp->fullBit(oldp+159,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp_wb2));
    bufp->fullBit(oldp+160,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__temp));
    bufp->fullCData(oldp+161,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp),8);
    bufp->fullBit(oldp+162,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp));
    bufp->fullBit(oldp+163,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out));
    bufp->fullWData(oldp+164,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__ram_initf),2048);
    bufp->fullIData(oldp+228,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__file_desc),32);
    bufp->fullBit(oldp+229,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__init_file_b_port));
    bufp->fullCData(oldp+230,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__wa_mult_x_ii),8);
    bufp->fullCData(oldp+231,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__wa_mult_x_iii),8);
    bufp->fullSData(oldp+232,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__add_reg_a_mult_wa),13);
    bufp->fullCData(oldp+233,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__add_reg_b_mult_wb),2);
    bufp->fullSData(oldp+234,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa),13);
    bufp->fullCData(oldp+235,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb),2);
    bufp->fullIData(oldp+236,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx),32);
    bufp->fullIData(oldp+237,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i2),32);
    bufp->fullIData(oldp+238,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i3),32);
    bufp->fullIData(oldp+239,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i4),32);
    bufp->fullIData(oldp+240,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i5),32);
    bufp->fullIData(oldp+241,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j),32);
    bufp->fullIData(oldp+242,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j2),32);
    bufp->fullIData(oldp+243,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__k),32);
    bufp->fullIData(oldp+244,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__k2),32);
    bufp->fullIData(oldp+245,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__k3),32);
    bufp->fullIData(oldp+246,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__k4),32);
    bufp->fullIData(oldp+247,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__i_div_wa),32);
    bufp->fullIData(oldp+248,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j_plus_i2),32);
    bufp->fullIData(oldp+249,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j2_plus_i5),32);
    bufp->fullIData(oldp+250,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j_plus_i2_div_a),32);
    bufp->fullIData(oldp+251,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__j2_plus_i5_div_a),32);
    bufp->fullBit(oldp+252,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_ACEX1K__Vstatic__is_acex1k));
    bufp->fullBit(oldp+253,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_APEX20K__Vstatic__is_apex20k));
    bufp->fullBit(oldp+254,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_APEX20KC__Vstatic__is_apex20kc));
    bufp->fullBit(oldp+255,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_APEX20KE__Vstatic__is_apex20ke));
    bufp->fullBit(oldp+256,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_APEXII__Vstatic__is_apexii));
    bufp->fullBit(oldp+257,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_EXCALIBUR_ARM__Vstatic__is_excalibur_arm));
    bufp->fullBit(oldp+258,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_FLEX10KE__Vstatic__is_flex10ke));
    bufp->fullBit(oldp+259,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_MERCURY__Vstatic__is_mercury));
    bufp->fullBit(oldp+260,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_CYCLONE__Vstatic__is_cyclone));
    bufp->fullBit(oldp+261,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_FAMILY_MAXII__Vstatic__is_maxii));
    bufp->fullBit(oldp+262,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_STRATIXGX__Vstatic__var_family_stratixgx));
    bufp->fullBit(oldp+263,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_CYCLONE__Vstatic__var_family_cyclone));
    bufp->fullBit(oldp+264,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_STRATIX__Vstatic__var_family_stratix));
    bufp->fullBit(oldp+265,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_MAXII__Vstatic__var_family_maxii));
    bufp->fullBit(oldp+266,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__FEATURE_FAMILY_HAS_INVERTED_OUTPUT_DDIO__Vstatic__var_family_has_inverted_output_ddio));
    bufp->fullBit(oldp+267,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__dev__DOT__IS_VALID_FAMILY__Vstatic__is_valid));
    bufp->fullCData(oldp+268,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__c),8);
    bufp->fullCData(oldp+269,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__hex),4);
    bufp->fullCData(oldp+270,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__tmp_char),4);
    bufp->fullIData(oldp+271,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__ifp),32);
    bufp->fullIData(oldp+272,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__ofp),32);
    bufp->fullIData(oldp+273,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__r),32);
    bufp->fullIData(oldp+274,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__r2),32);
    bufp->fullIData(oldp+275,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__i),32);
    bufp->fullIData(oldp+276,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__j),32);
    bufp->fullIData(oldp+277,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__k),32);
    bufp->fullIData(oldp+278,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__m),32);
    bufp->fullIData(oldp+279,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__n),32);
    bufp->fullIData(oldp+280,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__done),32);
    bufp->fullIData(oldp+281,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__error_status),32);
    bufp->fullIData(oldp+282,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__first_rec),32);
    bufp->fullIData(oldp+283,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__last_rec),32);
    bufp->fullIData(oldp+284,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__off_addr),32);
    bufp->fullIData(oldp+285,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__nn),32);
    bufp->fullIData(oldp+286,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__aaaa),32);
    bufp->fullIData(oldp+287,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__tt),32);
    bufp->fullIData(oldp+288,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__cc),32);
    bufp->fullIData(oldp+289,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__aah),32);
    bufp->fullIData(oldp+290,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__aal),32);
    bufp->fullIData(oldp+291,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__dd),32);
    bufp->fullIData(oldp+292,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__sum),32);
    bufp->fullIData(oldp+293,(vlSelf->testcase__DOT__inst_harness__DOT__u_MPI__DOT__u_STM__DOT__u_SPRAM__DOT__altsyncram_component__DOT__mem__DOT__convert_hex2ver__Vstatic__line_no),32);
}
